[package]
name = "penguin-game"
version = "0.1.0"
edition = "2024"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = "s"
strip = "symbols"

[dependencies]
glam = { version = "0.27", default-features = false }
nalgebra = { version = "0.34", default-features = false }
arrayvec = "0.7"
macroquad = "0.4"
miniquad = "0.4" # should be pinned by macroquad
parry2d = { version = "0.25", default-features = false, features = [
    "required-features",
    "alloc",
] }
image = { version = "0.24", default-features = false, features = ["png"] }
thiserror = "2"
enumset = "=1.1.10"
