edition = "2024"
style_edition = "2024"
unstable_features = true

use_small_heuristics = "Max"

imports_layout = "Vertical"
overflow_delimited_expr = true
short_array_element_width_threshold = 32
use_field_init_shorthand = true