#![allow(clippy::excessive_precision, clippy::pedantic)]
/// This code is generated by `@/tiled/generate_code.py`.
/// Generated from file `test_level.tmj` on `2025-12-20 01:37:54.966030+00:00`.
use std::rc::Rc;

use glam::{vec2, Vec2};

use crate::levels::*;

#[rustfmt::skip]
#[inline(never)]
pub fn build(mut builder: LevelBuilder) -> Level {
    builder.rect(Some("bricks"), vec2(1188., 7284.), vec2(4692., 24.)); // id=4
    builder.rect(Some("barrier"), vec2(1224., 4764.), vec2(24., 2040.)); // id=27
    builder.rect(Some("barrier"), vec2(10080., 4080.), vec2(24., 1872.)); // id=28
    builder.polygon_graphics("wood_dark", &[vec2(1380., 7284.), vec2(1404., 7236.), vec2(1416., 7236.), vec2(1392., 7284.), vec2(1380., 7284.)]); // id=30
    builder.polygon_graphics("wood_dark", &[vec2(1452., 7284.), vec2(1428., 7236.), vec2(1416., 7236.), vec2(1440., 7284.), vec2(1452., 7284.)]); // id=31
    builder.rect_graphics("bricks_dark", vec2(1848., 7224.), vec2(72., 60.)); // id=32
    builder.rect(Some("bricks"), vec2(1836., 7200.), vec2(96., 24.)); // id=33
    builder.rect(Some("caution"), vec2(1920., 7224.), vec2(12., 60.)); // id=35
    builder.rect(Some("barrier"), vec2(1224., 6888.), vec2(24., 396.)); // id=36
    builder.rect_graphics("barrier", vec2(1224., 6804.), vec2(24., 84.)); // id=37
    builder.rect_graphics("wood_dark", vec2(1248., 6864.), vec2(132., 12.)); // id=38
    builder.rect_graphics("wood_dark", vec2(1272., 6876.), vec2(12., 12.)); // id=39
    builder.rect_graphics("wood_dark", vec2(1344., 6876.), vec2(12., 12.)); // id=40
    builder.polygon(Some("caution"), &[vec2(1260., 6936.), vec2(1260., 6888.), vec2(1368., 6888.), vec2(1392., 6912.), vec2(1368., 6936.)]); // id=42
    builder.rect(Some("barrier"), vec2(276., 5976.), vec2(12., 1668.)); // id=44
    builder.rect_graphics("bricks_dark", vec2(1128., 7884.), vec2(72., 60.)); // id=45
    builder.rect(Some("bricks"), vec2(1104., 7944.), vec2(264., 12.)); // id=47
    builder.polygon(Some("barrier"), &[vec2(1104., 7956.), vec2(1104., 7944.), vec2(288., 7632.), vec2(288., 7644.)]); // id=48
    builder.rect(None, vec2(1368., 7308.), vec2(12., 648.)); // id=49
    builder.polygon_graphics("wood_dark", &[vec2(1116., 7884.), vec2(1212., 7884.), vec2(1164., 7836.)]); // id=50
    builder.polygon_graphics("bricks_dark", &[vec2(1200., 7872.), vec2(1188., 7860.), vec2(1188., 7836.), vec2(1200., 7836.), vec2(1200., 7872.)]); // id=52
    builder.rect(Some("bricks"), vec2(1008., 7776.), vec2(48., 12.)); // id=55
    builder.polygon(Some("caution"), &[vec2(1380., 7260.), vec2(1380., 7212.), vec2(1452., 7212.), vec2(1464., 7236.), vec2(1452., 7260.)]); // id=56
    builder.rect_graphics("bricks_dark", vec2(2172., 7116.), vec2(72., 168.)); // id=57
    builder.rect(Some("bricks"), vec2(2160., 7092.), vec2(96., 24.)); // id=58
    builder.rect(Some("caution"), vec2(2244., 7116.), vec2(12., 168.)); // id=59
    builder.rect_graphics("bricks_dark", vec2(2592., 7068.), vec2(72., 216.)); // id=60
    builder.rect(Some("bricks"), vec2(2580., 7044.), vec2(96., 24.)); // id=61
    builder.rect(Some("caution"), vec2(2664., 7068.), vec2(12., 216.)); // id=62
    builder.rect(Some("barrier"), vec2(2328., 6564.), vec2(24., 480.)); // id=63
    builder.rect(Some("barrier"), vec2(2784., 6564.), vec2(24., 456.)); // id=65
    builder.rect_graphics("bricks_dark", vec2(3000., 7008.), vec2(72., 276.)); // id=66
    builder.rect(Some("bricks"), vec2(2988., 6984.), vec2(96., 24.)); // id=67
    builder.rect(Some("caution"), vec2(3072., 7008.), vec2(12., 276.)); // id=68
    builder.rect(Some("barrier"), vec2(3144., 6564.), vec2(24., 456.)); // id=69
    builder.rect_graphics("bricks_dark", vec2(3312., 6984.), vec2(72., 300.)); // id=70
    builder.rect(Some("bricks"), vec2(3300., 6964.), vec2(96., 24.)); // id=71
    builder.rect(Some("caution"), vec2(3384., 6988.), vec2(12., 236.)); // id=72
    builder.rect(Some("wood"), vec2(3456., 3804.), vec2(24., 3276.)); // id=73
    builder.polygon_graphics("barrier", &[vec2(2280., 6564.), vec2(2316., 6444.), vec2(2400., 6564.)]); // id=83
    builder.polygon_graphics("caution", &[vec2(1256.94, 7881.709), vec2(1260.254, 7870.33), vec2(1266.22, 7870.883), vec2(1267.325, 7883.146)]); // id=84
    builder.polygon(Some("caution"), &[vec2(1256.912, 7881.709), vec2(1253.494, 7886.559), vec2(1253.167, 7894.405), vec2(1254.329, 7905.172), vec2(1261.635, 7917.421), vec2(1272.862, 7929.247), vec2(1284.565, 7935.668), vec2(1297.926, 7940.041), vec2(1267.545, 7883.367)]); // id=85
    builder.polygon(Some("caution"), &[vec2(1277.576, 7903.077), vec2(1292.074, 7914.978), vec2(1306.523, 7917.977), vec2(1298.148, 7939.93)]); // id=86
    builder.polygon(Some("caution"), &[vec2(1305.107, 7918.), vec2(1330.075, 7914.3), vec2(1343.995, 7912.753), vec2(1347.406, 7915.209), vec2(1347.088, 7920.486), vec2(1338.029, 7931.313), vec2(1310.3, 7940.814), vec2(1298.147, 7940.151)]); // id=87
    builder.rect(Some("bricks_dark"), vec2(1259.315, 7863.48), vec2(8.037, 7.706)); // id=88
    builder.rect_graphics("question_mark", vec2(1644., 7260.), vec2(24., 24.)); // id=92
    builder.rect_graphics("question_mark", vec2(3168., 7260.), vec2(24., 24.)); // id=98
    builder.polygon_graphics("caution", &[vec2(3528.028, 7218.229), vec2(3531.342, 7206.85), vec2(3537.308, 7207.402), vec2(3538.413, 7219.665)]); // id=165
    builder.polygon(Some("caution"), &[vec2(3528., 7218.229), vec2(3524.582, 7223.078), vec2(3524.255, 7230.924), vec2(3525.418, 7241.691), vec2(3532.723, 7253.94), vec2(3543.95, 7265.766), vec2(3555.654, 7272.187), vec2(3570.832, 7276.924), vec2(3538.633, 7219.886)]); // id=166
    builder.polygon(Some("caution"), &[vec2(3548.665, 7239.596), vec2(3563.163, 7251.497), vec2(3577.611, 7254.497), vec2(3569.236, 7276.449)]); // id=167
    builder.polygon(Some("caution"), &[vec2(3576.195, 7254.52), vec2(3601.163, 7250.819), vec2(3615.083, 7249.272), vec2(3618.494, 7251.728), vec2(3618.176, 7257.006), vec2(3609.117, 7267.832), vec2(3581.388, 7277.333), vec2(3569.235, 7276.67)]); // id=168
    builder.rect(Some("bricks_dark"), vec2(3530.403, 7200.), vec2(8.037, 7.706)); // id=169
    builder.rect(Some("bricks"), vec2(3984., 6924.), vec2(24., 360.)); // id=178
    builder.rect(Some("bricks"), vec2(3888., 6564.), vec2(24., 516.)); // id=179
    builder.rect_graphics("question_mark", vec2(3828., 7260.), vec2(24., 24.)); // id=182
    builder.rect(Some("bricks"), vec2(4404., 6804.), vec2(24., 480.)); // id=185
    builder.rect(Some("barrier"), vec2(4128., 5964.), vec2(24., 960.)); // id=191
    builder.rect(Some("barrier"), vec2(4488., 5988.), vec2(24., 936.)); // id=196
    builder.rect(Some("bricks"), vec2(4848., 6684.), vec2(24., 600.)); // id=197
    builder.polygon_graphics("caution", &[vec2(4474.013, 5867.412), vec2(4485.524, 5864.593), vec2(4488.029, 5870.035), vec2(4477.961, 5877.124)]); // id=198
    builder.polygon(Some("caution"), &[vec2(4473.998, 5867.386), vec2(4468.089, 5866.851), vec2(4461.131, 5870.491), vec2(4452.388, 5876.881), vec2(4445.432, 5889.332), vec2(4440.804, 5904.968), vec2(4441.095, 5918.314), vec2(4444.583, 5933.828), vec2(4477.879, 5877.423)]); // id=199
    builder.polygon(Some("caution"), &[vec2(4465.824, 5895.964), vec2(4462.767, 5914.47), vec2(4467.394, 5928.483), vec2(4444.194, 5932.206)]); // id=200
    builder.polygon(Some("caution"), &[vec2(4466.664, 5927.267), vec2(4482.353, 5947.039), vec2(4490.653, 5958.32), vec2(4490.232, 5962.502), vec2(4485.502, 5964.866), vec2(4471.596, 5962.434), vec2(4449.504, 5943.17), vec2(4444.002, 5932.314)]); // id=201
    builder.polygon(Some("bricks_dark"), &[vec2(4490.984, 5860.35), vec2(4495.003, 5867.31), vec2(4488.33, 5871.163), vec2(4484.311, 5864.203)]); // id=202
    builder.rect_graphics("question_mark", vec2(4488., 5832.), vec2(24., 24.)); // id=204
    builder.rect(Some("barrier"), vec2(4368., 5964.), vec2(240., 24.)); // id=211
    builder.rect(Some("bricks"), vec2(5064., 5604.), vec2(24., 1440.)); // id=213
    builder.rect(Some("bricks"), vec2(5304., 6684.), vec2(24., 600.)); // id=214
    builder.polygon(Some("bricks"), &[vec2(5304., 6900.), vec2(5160., 6804.), vec2(5160., 6684.), vec2(5304., 6684.)]); // id=216
    builder.rect(Some("bricks"), vec2(5664., 5604.), vec2(24., 1440.)); // id=217
    builder.polygon(Some("barrier"), &[vec2(5112., 6012.), vec2(5658., 6558.), vec2(5641.029, 6574.971), vec2(5095.029, 6028.971)]); // id=218
    builder.rect(Some("bricks"), vec2(5856., 6444.), vec2(24., 840.)); // id=219
    builder.rect(Some("bricks"), vec2(5856., 5604.), vec2(24., 648.)); // id=224
    builder.rect(Some("barrier"), vec2(5664., 5592.), vec2(216., 12.)); // id=225
    builder.rect(Some("bricks"), vec2(5880., 6444.), vec2(1656., 24.)); // id=226
    builder.rect_graphics("caution", vec2(3384., 7224.), vec2(12., 58.)); // id=233
    builder.rect_graphics("question_mark", vec2(3348., 7260.), vec2(24., 24.)); // id=234
    builder.rect_graphics("barrier_eyepatch", vec2(3456., 7080.), vec2(48., 204.)); // id=241
    builder.rect_graphics("question_mark", vec2(3684., 7260.), vec2(24., 24.)); // id=242
    builder.rect_graphics("question_mark", vec2(2748., 7260.), vec2(24., 24.)); // id=244
    builder.rect_graphics("question_mark", vec2(2820., 7260.), vec2(24., 24.)); // id=245
    builder.rect_graphics("question_mark", vec2(1200., 7920.), vec2(24., 24.)); // id=104
    builder.rect_graphics("barrier_danger", vec2(4152., 6444.), vec2(24., 480.)); // id=252
    builder.rect_graphics("barrier_danger", vec2(4512., 6444.), vec2(24., 480.)); // id=254
    builder.polygon_graphics("barrier_danger", &[vec2(5088., 6900.), vec2(5208., 7044.), vec2(5088., 7044.)]); // id=261
    builder.rect_graphics("barrier_danger", vec2(5808., 6804.), vec2(48., 24.)); // id=268
    builder.rect_graphics("barrier_danger", vec2(5688., 6564.), vec2(48., 24.)); // id=269
    builder.rect_graphics("barrier_danger", vec2(5688., 7020.), vec2(48., 24.)); // id=263
    builder.rect(Some("bricks"), vec2(5880., 6228.), vec2(96., 24.)); // id=270
    builder.rect(Some("bricks"), vec2(6108., 6312.), vec2(84., 12.)); // id=271
    builder.rect(Some("bricks"), vec2(6096., 6144.), vec2(12., 180.)); // id=272
    builder.rect(Some("bricks"), vec2(6108., 6144.), vec2(144., 12.)); // id=273
    builder.rect(Some("bricks"), vec2(6252., 6144.), vec2(12., 180.)); // id=274
    builder.rect_graphics("question_mark", vec2(6204., 6420.), vec2(24., 24.)); // id=275
    builder.rect_graphics("barrier_move", vec2(6108., 6156.), vec2(48., 156.)); // id=278
    builder.polygon_graphics("caution", &[vec2(4531.122, 5863.06), vec2(4542.633, 5860.241), vec2(4545.138, 5865.683), vec2(4535.07, 5872.772)]); // id=280
    builder.polygon(Some("caution"), &[vec2(4531.112, 5863.04), vec2(4525.203, 5862.505), vec2(4518.245, 5866.145), vec2(4509.502, 5872.535), vec2(4502.546, 5884.986), vec2(4497.918, 5900.622), vec2(4498.209, 5913.968), vec2(4501.697, 5929.482), vec2(4534.993, 5873.077)]); // id=281
    builder.polygon(Some("caution"), &[vec2(4522.936, 5891.611), vec2(4519.879, 5910.117), vec2(4524.505, 5924.129), vec2(4501.306, 5927.852)]); // id=282
    builder.polygon(Some("caution"), &[vec2(4523.773, 5922.917), vec2(4539.462, 5942.689), vec2(4547.761, 5953.971), vec2(4547.34, 5958.153), vec2(4542.611, 5960.516), vec2(4528.705, 5958.084), vec2(4506.612, 5938.82), vec2(4501.11, 5927.965)]); // id=283
    builder.polygon(Some("bricks_dark"), &[vec2(4548.092, 5856.), vec2(4552.11, 5862.96), vec2(4545.437, 5866.813), vec2(4541.418, 5859.853)]); // id=284
    builder.polygon(Some("caution"), &[vec2(1632.103, 9060.684), vec2(1645.124, 9007.445), vec2(1672.797, 9008.796), vec2(1680.37, 9065.228)]); // id=290
    builder.polygon(Some("caution"), &[vec2(1632., 9060.682), vec2(1617.186, 9083.774), vec2(1617.256, 9120.089), vec2(1624.794, 9169.597), vec2(1661.011, 9224.718), vec2(1715.262, 9277.092), vec2(1770.626, 9304.402), vec2(1841.706, 9323.229), vec2(1681.46, 9066.197)]); // id=291
    builder.polygon(Some("caution"), &[vec2(1731.729, 9155.233), vec2(1801.106, 9207.295), vec2(1868.462, 9218.242), vec2(1834.188, 9321.35)]); // id=292
    builder.polygon(Some("caution"), &[vec2(1861.927, 9218.658), vec2(1976.532, 9196.532), vec2(2040.531, 9186.584), vec2(2056.784, 9197.242), vec2(2056.38, 9221.689), vec2(2016.707, 9273.532), vec2(1890.509, 9323.011), vec2(1834.232, 9322.396)]); // id=293
    builder.polygon(Some("bricks_dark"), &[vec2(1639.387, 8976.), vec2(1676.518, 8974.382), vec2(1678.07, 9009.982), vec2(1640.938, 9011.6)]); // id=294
    builder.rect(Some("wood"), vec2(1668., 8160.), vec2(12., 816.)); // id=296
    builder.rect(Some("wood"), vec2(1800., 8160.), vec2(12., 84.)); // id=297
    builder.rect(Some("wood"), vec2(1668., 8148.), vec2(144., 12.)); // id=298
    builder.rect(Some("wood"), vec2(1740., 8232.), vec2(60., 12.)); // id=299
    builder.rect(Some("wood"), vec2(1740., 8244.), vec2(12., 732.)); // id=300
    builder.polygon(Some("caution"), &[vec2(2429.481, 9178.733), vec2(2376.864, 9163.389), vec2(2364.197, 9188.03), vec2(2409.282, 9222.805)]); // id=308
    builder.polygon(Some("caution"), &[vec2(2429.532, 9178.643), vec2(2456.938, 9177.36), vec2(2488.352, 9195.578), vec2(2527.459, 9226.86), vec2(2557.086, 9285.786), vec2(2575.317, 9358.956), vec2(2571.286, 9420.557), vec2(2552.049, 9491.528), vec2(2409.578, 9224.234)]); // id=309
    builder.polygon(Some("caution"), &[vec2(2461.553, 9312.287), vec2(2471.952, 9398.401), vec2(2447.754, 9462.206), vec2(2554.185, 9484.079)]); // id=310
    builder.polygon(Some("caution"), &[vec2(2451.386, 9456.757), vec2(2374.921, 9544.945), vec2(2334.305, 9595.395), vec2(2335.409, 9614.8), vec2(2356.783, 9626.673), vec2(2421.517, 9618.238), vec2(2527.465, 9533.687), vec2(2555.072, 9484.641)]); // id=311
    builder.polygon(Some("bricks_dark"), &[vec2(2332.536, 9174.048), vec2(2352.504, 9142.7), vec2(2382.559, 9161.844), vec2(2362.591, 9193.192)]); // id=312
    builder.polygon(Some("caution"), &[vec2(1956.207, 10016.515), vec2(2020.872, 9919.193), vec2(2075.383, 9941.942), vec2(2049.699, 10060.583)]); // id=313
    builder.polygon(Some("caution"), &[vec2(1956., 10018.438), vec2(1909.572, 10054.013), vec2(1883.412, 10126.879), vec2(1862.67, 10231.611), vec2(1895.372, 10368.367), vec2(1966.224, 10512.674), vec2(2057.457, 10607.531), vec2(2186.351, 10696.76), vec2(2051.18, 10065.316)]); // id=314
    builder.polygon(Some("caution"), &[vec2(2087.499, 10278.269), vec2(2188.907, 10432.908), vec2(2308.038, 10524.973), vec2(2172.64, 10685.565)]); // id=315
    builder.polygon(Some("caution"), &[vec2(2307.955, 10527.741), vec2(3524.058, 11143.05), vec2(3447.906, 11283.138), vec2(2171.96, 10687.693)]); // id=316
    builder.polygon(Some("bricks_dark"), &[vec2(2032.147, 9852.), vec2(2107.774, 9875.647), vec2(2085.103, 9948.155), vec2(2009.476, 9924.508)]); // id=317
    builder.polygon(None, &[vec2(2036.806, 9233.861), vec2(2048.757, 9232.779), vec2(2107.194, 9878.139), vec2(2095.243, 9879.221)]); // id=325
    builder.polygon(None, &[vec2(1752., 8976.), vec2(1755.601, 8964.553), vec2(2331.253, 9145.66), vec2(2327.652, 9157.107)]); // id=326
    builder.polygon(None, &[vec2(2374.75, 9630.914), vec2(2382.146, 9621.464), vec2(3060.098, 10152.114), vec2(3052.702, 10161.564)]); // id=327
    builder.polygon(None, &[vec2(3049.191, 10146.908), vec2(3057.602, 10138.349), vec2(4070.117, 11133.347), vec2(4061.706, 11141.906)]); // id=330
    builder.polygon_graphics("barrier_danger", &[vec2(3936.054, 11114.687), vec2(3963.388, 11162.192), vec2(3942.436, 11180.32), vec2(3897.998, 11144.722)]); // id=332
    builder.polygon_graphics("barrier_danger", &[vec2(3936.129, 11114.616), vec2(3930.904, 11087.683), vec2(3905.783, 11061.459), vec2(3866.15, 11030.846), vec2(3801.895, 11015.971), vec2(3726.489, 11015.535), vec2(3667.582, 11033.999), vec2(3603.161, 11069.451), vec2(3896.54, 11144.772)]); // id=333
    builder.polygon_graphics("barrier_danger", &[vec2(3798.703, 11115.06), vec2(3712.569, 11125.292), vec2(3656.282, 11163.873), vec2(3609.895, 11065.617)]); // id=334
    builder.polygon_graphics("barrier_danger", &[vec2(3661.68, 11159.338), vec2(3594.043, 11254.466), vec2(3554.611, 11305.846), vec2(3535.494, 11309.356), vec2(3518.91, 11291.39), vec2(3511.82, 11226.495), vec2(3568.96, 11103.577), vec2(3610.099, 11065.169)]); // id=335
    builder.polygon_graphics("barrier_danger", &[vec2(3989.245, 11180.978), vec2(3963.5, 11207.783), vec2(3937.799, 11183.099), vec2(3963.545, 11156.294)]); // id=336
    builder.rect_graphics("question_mark", vec2(4080., 7260.), vec2(24., 24.)); // id=338
    builder.rect_graphics("barrier_no_eyepatch", vec2(5928., 6252.), vec2(48., 192.)); // id=348
    builder.rect(Some("bricks"), vec2(3480., 7044.), vec2(24., 36.)); // id=349
    builder.rect(Some("wood"), vec2(6360., 4056.), vec2(24., 2280.)); // id=350
    builder.rect_trigger(TriggerKind::ShowText(Rc::from("Shoot a rocket under yourself to\nlaunch yourself into the air.")), vec2(1644., 7260.), vec2(24., 24.)); // id=99
    builder.polygon_trigger(TriggerKind::Goto(LEVEL_OBJECT_295, StatusIcon::Nice), &[vec2(1250.455, 7882.182), vec2(1259.333, 7864.), vec2(1267., 7863.667), vec2(1347.667, 7913.667), vec2(1349., 7926.), vec2(1311.333, 7944.667), vec2(1274.333, 7933.667), vec2(1252.333, 7907.667)]); // id=101
    builder.polygon_trigger(TriggerKind::Hello, &[vec2(2280., 6564.), vec2(2316., 6444.), vec2(2400., 6564.)]); // id=102
    builder.rect_trigger(TriggerKind::ShowText(Rc::from("This one is tricky!\nBut still possible with one rocket jump.\nHarness the power of penguin jank.")), vec2(3168., 7260.), vec2(24., 24.)); // id=103
    builder.rect_trigger(TriggerKind::ShowText(Rc::from("banana secret")), vec2(1200., 7920.), vec2(24., 24.)); // id=105
    builder.polygon_trigger(TriggerKind::ShowText(Rc::from("banana")), &[vec2(3528., 7284.), vec2(3516., 7200.), vec2(3552., 7188.), vec2(3624., 7248.), vec2(3612., 7284.)]); // id=184
    builder.rect_trigger(TriggerKind::ShowText(Rc::from("You can rocket jump off of\nwalls too.")), vec2(3828., 7260.), vec2(24., 24.)); // id=183
    builder.rect_trigger(TriggerKind::ShowText(Rc::from("you made it this high!\nthat's bananas")), vec2(4488., 5832.), vec2(24., 24.)); // id=205
    builder.rect_trigger(TriggerKind::ShowText(Rc::from("If you can't make this jump,\nthere's a hidden hole ---->")), vec2(3348., 7260.), vec2(24., 24.)); // id=235
    builder.rect_trigger(TriggerKind::SetEyepatch(true), vec2(3456., 7080.), vec2(48., 204.)); // id=236
    builder.rect_trigger(TriggerKind::SetEyepatch(false), vec2(5928., 6252.), vec2(48., 192.)); // id=240
    builder.rect_trigger(TriggerKind::ShowText(Rc::from("The eyepatch means that you cannot\nshoot rockets when another rocket\nis already in flight.")), vec2(3684., 7260.), vec2(24., 24.)); // id=243
    builder.rect_trigger(TriggerKind::ShowText(Rc::from("The penguin has a \"fuel meter\"\ndisplayed on its body. When you\nare out of fuel, you cannot shoot.")), vec2(2748., 7260.), vec2(24., 24.)); // id=246
    builder.rect_trigger(TriggerKind::ShowText(Rc::from("Try aiming in the air and holding\nthe left mouse button to understand\nthe mechanism better.")), vec2(2820., 7260.), vec2(24., 24.)); // id=247
    builder.rect_trigger(TriggerKind::Goto(LEVEL_OBJECT_253, StatusIcon::Wrong), vec2(4152., 6444.), vec2(24., 480.)); // id=251
    const LEVEL_OBJECT_253: Vec2 = vec2(4248., 7236.); // id=253
    builder.rect_trigger(TriggerKind::Goto(LEVEL_OBJECT_256, StatusIcon::Wrong), vec2(4512., 6444.), vec2(24., 480.)); // id=255
    const LEVEL_OBJECT_256: Vec2 = vec2(4608., 7260.); // id=256
    builder.polygon_trigger(TriggerKind::Goto(LEVEL_OBJECT_262, StatusIcon::Wrong), &[vec2(5088., 6900.), vec2(5208., 7044.), vec2(5088., 7044.)]); // id=260
    const LEVEL_OBJECT_262: Vec2 = vec2(5088., 7260.); // id=262
    builder.rect_trigger(TriggerKind::Goto(LEVEL_OBJECT_265, StatusIcon::Wrong), vec2(5688., 7020.), vec2(48., 24.)); // id=264
    const LEVEL_OBJECT_265: Vec2 = vec2(5688., 7260.); // id=265
    builder.rect_trigger(TriggerKind::Goto(LEVEL_OBJECT_265, StatusIcon::Wrong), vec2(5808., 6804.), vec2(48., 24.)); // id=266
    builder.rect_trigger(TriggerKind::Goto(LEVEL_OBJECT_265, StatusIcon::Wrong), vec2(5688., 6564.), vec2(48., 24.)); // id=267
    builder.rect_trigger(TriggerKind::ShowText(Rc::from("Go to the start")), vec2(6204., 6420.), vec2(24., 24.)); // id=276
    builder.rect_trigger(TriggerKind::Goto(LEVEL_OBJECT_279, StatusIcon::Nice), vec2(6108., 6156.), vec2(48., 156.)); // id=277
    const LEVEL_OBJECT_279: Vec2 = vec2(1548., 7260.); // id=279
    const LEVEL_OBJECT_295: Vec2 = vec2(1764., 8208.); // id=295
    builder.polygon_trigger(TriggerKind::Panic, &[vec2(3512.102, 11197.056), vec2(3587.141, 11078.979), vec2(3635.698, 11038.74), vec2(3755.309, 11002.555), vec2(3893.962, 11034.182), vec2(4029.41, 11186.099), vec2(3755.931, 11362.335), vec2(3525.821, 11279.989), vec2(3507.627, 11261.414)]); // id=337
    builder.rect_trigger(TriggerKind::ShowText(Rc::from("Unlike real rockets, penguin rockets\ndon't inherit your velocity. E.g. if\nyou shoot a rocket directly downward\nwhile moving right, the rocket will\nexplode when it's to the left of you")), vec2(4080., 7260.), vec2(24., 24.)); // id=339
    builder.rect_graphics("question_mark", vec2(4464., 7260.), vec2(24., 24.)); // id=340
    builder.rect_trigger(TriggerKind::ShowText(Rc::from("The game runs at 240 ticks/second.\nThe penguin's radius is 24.\nThe explosion radius is 42.\nExplosions live for 8 ticks.\nJust in case you like numbers.")), vec2(4464., 7260.), vec2(24., 24.)); // id=341
    builder.rect_graphics("wood_dark", vec2(6360., 6336.), vec2(24., 108.)); // id=351
    builder.rect(Some("bricks"), vec2(1332., 6216.), vec2(84., 12.)); // id=352
    builder.rect(Some("bricks"), vec2(1320., 6048.), vec2(12., 180.)); // id=353
    builder.rect(Some("bricks"), vec2(1332., 6048.), vec2(144., 12.)); // id=354
    builder.rect(Some("bricks"), vec2(1476., 6048.), vec2(12., 660.)); // id=355
    builder.rect_graphics("barrier_move", vec2(1332., 6060.), vec2(48., 156.)); // id=356
    builder.rect_trigger(TriggerKind::Goto(LEVEL_OBJECT_359, StatusIcon::Nice), vec2(1332., 6060.), vec2(48., 156.)); // id=357
    const LEVEL_OBJECT_359: Vec2 = vec2(6084., 6420.); // id=359
    builder.rect(Some("bricks"), vec2(1380., 6684.), vec2(96., 24.)); // id=360
    builder.rect_graphics("question_mark", vec2(1415.333, 6660.), vec2(24., 24.)); // id=362
    builder.rect_trigger(TriggerKind::ShowText(Rc::from("Part2  ^\n       |")), vec2(1415.333, 6660.), vec2(24., 24.)); // id=363
    builder.rect_graphics("question_mark", vec2(6408., 6420.), vec2(24., 24.)); // id=364
    builder.rect_trigger(TriggerKind::ShowText(Rc::from("You can get pushed away by two\nexplosions at once. Their impacts\nwill be combined, so you'll fly\naway much further than with a\nsingle explosion.")), vec2(6408., 6420.), vec2(24., 24.)); // id=365
    builder.rect_graphics("question_mark", vec2(6480., 6420.), vec2(24., 24.)); // id=366
    builder.rect_trigger(TriggerKind::ShowText(Rc::from("1. Jump vertically\n2. When you just start falling down,\n   shoot a rocket downwards.\n3. Once you catch up to the rocket due\n   to gravity, shoot the second rocket.")), vec2(6480., 6420.), vec2(24., 24.)); // id=367
    builder.rect_graphics("question_mark", vec2(6552., 6420.), vec2(24., 24.)); // id=368
    builder.rect_trigger(TriggerKind::ShowText(Rc::from("Because the rockets were around the same position\nat some point, they will impact the ground at\nabout the same time. If you don't get the timing\nright, you'll miss one of the explosions.")), vec2(6552., 6420.), vec2(24., 24.)); // id=369
    builder.rect(Some("bricks"), vec2(7008., 5628.), vec2(12., 672.)); // id=372
    builder.rect(Some("bricks"), vec2(7188., 5820.), vec2(12., 624.)); // id=373
    const LEVEL_OBJECT_374: Vec2 = vec2(7044., 6420.); // id=374
    builder.rect(Some("bricks"), vec2(7164., 5808.), vec2(36., 12.)); // id=377
    builder.rect_graphics("barrier_danger", vec2(7020., 5760.), vec2(12., 540.)); // id=379
    builder.rect_graphics("barrier_danger", vec2(7176., 5820.), vec2(12., 480.)); // id=380
    builder.rect_trigger(TriggerKind::Goto(LEVEL_OBJECT_374, StatusIcon::Wrong), vec2(7176., 5820.), vec2(12., 480.)); // id=378
    builder.rect_trigger(TriggerKind::Goto(LEVEL_OBJECT_374, StatusIcon::Wrong), vec2(7020., 5760.), vec2(12., 540.)); // id=370
    builder.rect(Some("bricks"), vec2(7296., 5280.), vec2(12., 1056.)); // id=381
    builder.rect(Some("bricks"), vec2(7524., 5472.), vec2(12., 972.)); // id=385
    builder.rect_trigger(TriggerKind::Goto(LEVEL_OBJECT_391, StatusIcon::Wrong), vec2(7308., 5472.), vec2(12., 864.)); // id=386
    builder.rect_trigger(TriggerKind::Goto(LEVEL_OBJECT_391, StatusIcon::Wrong), vec2(7512., 5472.), vec2(12., 864.)); // id=387
    builder.rect(Some("bricks"), vec2(7512., 5460.), vec2(240., 12.)); // id=389
    builder.rect(Some("bricks"), vec2(7308., 5280.), vec2(324., 12.)); // id=390
    const LEVEL_OBJECT_391: Vec2 = vec2(7320., 6420.); // id=391
    builder.rect_graphics("barrier_danger", vec2(7308., 5472.), vec2(12., 864.)); // id=392
    builder.rect_graphics("barrier_danger", vec2(7512., 5472.), vec2(12., 864.)); // id=393
    builder.rect(Some("bricks"), vec2(7368., 5568.), vec2(48., 48.)); // id=394
    builder.rect(Some("bricks"), vec2(7752., 5460.), vec2(12., 204.)); // id=395
    builder.rect_graphics("question_mark", vec2(7560., 5436.), vec2(24., 24.)); // id=396
    builder.rect_trigger(TriggerKind::ShowText(Rc::from("Now we turn the croco-dial to 11.")), vec2(7560., 5436.), vec2(24., 24.)); // id=397
    builder.rect_graphics("water", vec2(7764., 5568.), vec2(684., 96.)); // id=408
    builder.rect_trigger(TriggerKind::Goto(LEVEL_OBJECT_410, StatusIcon::Wrong), vec2(7764., 5568.), vec2(684., 96.)); // id=409
    const LEVEL_OBJECT_410: Vec2 = vec2(7668., 5436.); // id=410
    builder.rect(Some("crocodile4"), vec2(8112., 5448.), vec2(84., 24.)); // id=411
    builder.rect_trigger(TriggerKind::Goto(LEVEL_OBJECT_410, StatusIcon::Wrong), vec2(8112., 5448.), vec2(132.375, 24.)); // id=412
    builder.rect(Some("bricks"), vec2(8448., 5460.), vec2(336., 108.)); // id=413
    builder.rect(Some("bricks"), vec2(7752., 5664.), vec2(1080., 12.)); // id=414
    builder.rect_trigger(TriggerKind::SetEyepatch(true), vec2(7608., 5328.), vec2(24., 132.)); // id=422
    builder.rect_graphics("barrier_eyepatch", vec2(7608., 5328.), vec2(24., 132.)); // id=424
    builder.polygon_trigger(TriggerKind::Goto(LEVEL_OBJECT_410, StatusIcon::Wrong), &[vec2(7752.697, 5243.349), vec2(7758.697, 5253.741), vec2(7626.605, 5330.004), vec2(7620.605, 5319.612)]); // id=425
    builder.rect_trigger(TriggerKind::Goto(LEVEL_OBJECT_410, StatusIcon::Wrong), vec2(7752., 5244.), vec2(720., 12.)); // id=426
    builder.rect(Some("bricks"), vec2(8424., 5484.), vec2(24., 84.)); // id=430
    builder.polygon(Some("bricks"), &[vec2(8472., 5460.), vec2(8616., 5400.), vec2(8616., 5460.)]); // id=431
    builder.rect_trigger(TriggerKind::SetEyepatch(false), vec2(7512., 5328.), vec2(24., 132.)); // id=432
    builder.rect_graphics("barrier_no_eyepatch", vec2(7512., 5328.), vec2(24., 132.)); // id=433
    builder.rect(Some("crocodile4"), vec2(8196., 5448.), vec2(48., 24.)); // id=434
    builder.polygon(Some("bricks"), &[vec2(8424., 5472.), vec2(8436., 5460.), vec2(8448., 5460.), vec2(8448., 5484.), vec2(8424., 5484.)]); // id=435
    builder.polygon(Some("barrier_danger"), &[vec2(7752.704, 5243.455), vec2(7758.704, 5253.847), vec2(7626.612, 5330.11), vec2(7620.612, 5319.718)]); // id=437
    builder.rect(Some("barrier_danger"), vec2(7752., 5244.), vec2(720., 12.)); // id=438
    builder.polygon(Some("bricks"), &[vec2(8621.304, 5399.957), vec2(8627.739, 5393.522), vec2(8634.174, 5399.957)]); // id=441
    builder.rect(Some("bricks"), vec2(8616., 5401.), vec2(168., 59.)); // id=442
    builder.rect(Some("bricks"), vec2(7512., 5292.), vec2(120., 36.)); // id=443
    builder.rect(Some("bricks"), vec2(6708., 5760.), vec2(12., 540.)); // id=445
    builder.rect(Some("bricks"), vec2(6840., 5820.), vec2(12., 624.)); // id=446
    builder.polygon(Some("bricks"), &[vec2(6852., 5616.), vec2(6860.485, 5624.485), vec2(6716.256, 5768.714), vec2(6707.771, 5760.229)]); // id=447
    builder.rect(Some("bricks"), vec2(6840., 5808.), vec2(36., 12.)); // id=448
    builder.rect(Some("bricks"), vec2(6852., 5616.), vec2(444., 12.)); // id=453
    builder.polygon(Some("bricks"), &[vec2(7032., 5760.), vec2(7164., 5628.), vec2(7020., 5628.), vec2(7020., 5760.)]); // id=454
    builder.rect_trigger(TriggerKind::ShowText(Rc::from("Try to climb this tower without wall-jumping")), vec2(6624., 6420.), vec2(24., 24.)); // id=455
    builder.rect_graphics("question_mark", vec2(6624., 6420.), vec2(24., 24.)); // id=456
    builder.rect_trigger(TriggerKind::Goto(LEVEL_OBJECT_459, StatusIcon::Wrong), vec2(8472., 5208.), vec2(720., 12.)); // id=458
    const LEVEL_OBJECT_459: Vec2 = vec2(8688., 5388.); // id=459
    builder.rect(Some("bricks"), vec2(9840., 5868.), vec2(240., 84.)); // id=461
    builder.rect(Some("bricks"), vec2(8472., 5172.), vec2(720., 12.)); // id=464
    builder.rect_trigger(TriggerKind::SetEyepatch(true), vec2(8652., 5376.), vec2(24., 24.)); // id=466
    builder.polygon_graphics("water", &[vec2(8784., 5664.), vec2(8784., 5568.), vec2(9504., 5904.), vec2(9504., 5904.), vec2(9504., 5952.), vec2(9504., 5952.), vec2(8832., 5664.)]); // id=467
    builder.polygon_trigger(TriggerKind::Goto(LEVEL_OBJECT_459, StatusIcon::Wrong), &[vec2(8784., 5664.), vec2(8784., 5568.), vec2(9504., 5904.), vec2(9504., 5952.), vec2(8832., 5664.)]); // id=468
    builder.polygon(Some("bricks"), &[vec2(8832., 5664.), vec2(9504., 5952.), vec2(8832., 5952.)]); // id=469
    builder.rect_graphics("barrier_danger", vec2(8472., 5184.), vec2(720., 36.)); // id=470
    builder.rect(Some("water"), vec2(8448., 5568.), vec2(336., 96.)); // id=472
    builder.polygon_trigger(TriggerKind::Goto(LEVEL_OBJECT_459, StatusIcon::Wrong), &[vec2(9504., 5904.), vec2(9672., 5904.), vec2(9672., 5952.), vec2(9504., 5952.)]); // id=473
    builder.polygon(Some("bricks"), &[vec2(9672., 5952.), vec2(9672., 5903.25), vec2(9840., 5868.), vec2(9840., 5952.)]); // id=474
    builder.rect_graphics("water", vec2(9504., 5904.), vec2(168., 48.)); // id=475
    builder.rect_trigger(TriggerKind::ShowText(Rc::from("to be continued")), vec2(9912., 5844.), vec2(96., 24.)); // id=476
    builder.level_start(vec2(1524., 7260.));
    builder.build_or_die()
}
