#![allow(clippy::excessive_precision, clippy::pedantic)]
/// This code is generated by `@/tiled/generate_code.py`.
/// Generated from file `test_level.tmj` on `2025-11-28 05:30:46.137949+00:00`.
use crate::levels;
use glam::vec2;

#[rustfmt::skip]
#[inline(never)]
pub fn build(mut builder: levels::LevelBuilder) -> levels::Level {
    builder.rect(Some("bricks"), vec2(-540., 120.), vec2(4644., 24.)); // id=4
    builder.rect(Some("barrier"), vec2(-504., -2400.), vec2(24., 2040.)); // id=27
    builder.rect(Some("barrier"), vec2(6396., -2400.), vec2(24., 1704.)); // id=28
    builder.polygon_graphics("wood_dark", &[vec2(-348., 120.), vec2(-324., 72.), vec2(-312., 72.), vec2(-336., 120.), vec2(-348., 120.)]); // id=30
    builder.polygon_graphics("wood_dark", &[vec2(-276., 120.), vec2(-300., 72.), vec2(-312., 72.), vec2(-288., 120.), vec2(-276., 120.)]); // id=31
    builder.rect_graphics("bricks_dark", vec2(120., 60.), vec2(72., 60.)); // id=32
    builder.rect(Some("bricks"), vec2(108., 36.), vec2(96., 24.)); // id=33
    builder.rect(Some("caution"), vec2(192., 60.), vec2(12., 60.)); // id=35
    builder.rect(Some("barrier"), vec2(-504., -276.), vec2(24., 396.)); // id=36
    builder.rect_graphics("barrier", vec2(-504., -360.), vec2(24., 84.)); // id=37
    builder.rect_graphics("wood_dark", vec2(-480., -300.), vec2(132., 12.)); // id=38
    builder.rect_graphics("wood_dark", vec2(-456., -288.), vec2(12., 12.)); // id=39
    builder.rect_graphics("wood_dark", vec2(-384., -288.), vec2(12., 12.)); // id=40
    builder.polygon(Some("caution"), &[vec2(-468., -228.), vec2(-468., -276.), vec2(-360., -276.), vec2(-336., -252.), vec2(-360., -228.)]); // id=42
    builder.rect(Some("barrier"), vec2(-1452., -1188.), vec2(12., 1668.)); // id=44
    builder.rect_graphics("bricks_dark", vec2(-600., 720.), vec2(72., 60.)); // id=45
    builder.rect(Some("bricks"), vec2(-624., 780.), vec2(264., 12.)); // id=47
    builder.polygon(Some("barrier"), &[vec2(-624., 792.), vec2(-624., 780.), vec2(-1440., 468.), vec2(-1440., 480.)]); // id=48
    builder.rect(None, vec2(-360., 144.), vec2(12., 648.)); // id=49
    builder.polygon_graphics("wood_dark", &[vec2(-612., 720.), vec2(-516., 720.), vec2(-564., 672.)]); // id=50
    builder.polygon_graphics("bricks_dark", &[vec2(-528., 708.), vec2(-540., 696.), vec2(-540., 672.), vec2(-528., 672.), vec2(-528., 708.)]); // id=52
    builder.rect(Some("bricks"), vec2(-720., 612.), vec2(48., 12.)); // id=55
    builder.polygon(Some("caution"), &[vec2(-348., 96.), vec2(-348., 48.), vec2(-276., 48.), vec2(-264., 72.), vec2(-276., 96.)]); // id=56
    builder.rect_graphics("bricks_dark", vec2(444., -48.), vec2(72., 168.)); // id=57
    builder.rect(Some("bricks"), vec2(432., -72.), vec2(96., 24.)); // id=58
    builder.rect(Some("caution"), vec2(516., -48.), vec2(12., 168.)); // id=59
    builder.rect_graphics("bricks_dark", vec2(864., -96.), vec2(72., 216.)); // id=60
    builder.rect(Some("bricks"), vec2(852., -120.), vec2(96., 24.)); // id=61
    builder.rect(Some("caution"), vec2(936., -96.), vec2(12., 216.)); // id=62
    builder.rect(Some("barrier"), vec2(600., -600.), vec2(24., 480.)); // id=63
    builder.rect(Some("barrier"), vec2(1056., -600.), vec2(24., 456.)); // id=65
    builder.rect_graphics("bricks_dark", vec2(1272., -156.), vec2(72., 276.)); // id=66
    builder.rect(Some("bricks"), vec2(1260., -180.), vec2(96., 24.)); // id=67
    builder.rect(Some("caution"), vec2(1344., -156.), vec2(12., 276.)); // id=68
    builder.rect(Some("barrier"), vec2(1416., -600.), vec2(24., 456.)); // id=69
    builder.rect_graphics("bricks_dark", vec2(1584., -180.), vec2(72., 300.)); // id=70
    builder.rect(Some("bricks"), vec2(1572., -200.), vec2(96., 24.)); // id=71
    builder.rect(Some("caution"), vec2(1656., -176.), vec2(12., 236.)); // id=72
    builder.rect(Some("wood"), vec2(1728., -3360.), vec2(24., 3276.)); // id=73
    builder.polygon_graphics("barrier", &[vec2(552., -600.), vec2(588., -720.), vec2(672., -600.)]); // id=83
    builder.polygon_graphics("caution", &[vec2(-471.06, 717.709), vec2(-467.746, 706.33), vec2(-461.78, 706.883), vec2(-460.675, 719.146)]); // id=84
    builder.polygon(Some("caution"), &[vec2(-471.088, 717.709), vec2(-474.506, 722.559), vec2(-474.833, 730.405), vec2(-473.671, 741.172), vec2(-466.365, 753.421), vec2(-455.138, 765.247), vec2(-443.435, 771.668), vec2(-430.074, 776.041), vec2(-460.455, 719.367)]); // id=85
    builder.polygon(Some("caution"), &[vec2(-450.424, 739.077), vec2(-435.926, 750.978), vec2(-421.477, 753.977), vec2(-429.852, 775.93)]); // id=86
    builder.polygon(Some("caution"), &[vec2(-422.893, 754.), vec2(-397.925, 750.3), vec2(-384.005, 748.753), vec2(-380.594, 751.209), vec2(-380.912, 756.486), vec2(-389.971, 767.313), vec2(-417.7, 776.814), vec2(-429.853, 776.151)]); // id=87
    builder.rect(Some("bricks_dark"), vec2(-468.685, 699.48), vec2(8.037, 7.706)); // id=88
    builder.rect_graphics("question_mark", vec2(-84., 96.), vec2(24., 24.)); // id=92
    builder.rect_graphics("question_mark", vec2(1440., 96.), vec2(24., 24.)); // id=98
    builder.polygon_graphics("caution", &[vec2(1788.028, 54.229), vec2(1791.342, 42.85), vec2(1797.308, 43.402), vec2(1798.413, 55.665)]); // id=165
    builder.polygon(Some("caution"), &[vec2(1788., 54.229), vec2(1784.582, 59.078), vec2(1784.255, 66.924), vec2(1785.418, 77.691), vec2(1792.723, 89.94), vec2(1803.95, 101.766), vec2(1815.654, 108.187), vec2(1830.832, 112.924), vec2(1798.633, 55.886)]); // id=166
    builder.polygon(Some("caution"), &[vec2(1808.665, 75.596), vec2(1823.163, 87.497), vec2(1837.611, 90.497), vec2(1829.236, 112.449)]); // id=167
    builder.polygon(Some("caution"), &[vec2(1836.195, 90.52), vec2(1861.163, 86.819), vec2(1875.083, 85.272), vec2(1878.494, 87.728), vec2(1878.176, 93.006), vec2(1869.117, 103.832), vec2(1841.388, 113.333), vec2(1829.235, 112.67)]); // id=168
    builder.rect(Some("bricks_dark"), vec2(1790.403, 36.), vec2(8.037, 7.706)); // id=169
    builder.rect(Some("bricks"), vec2(2256., -240.), vec2(24., 360.)); // id=178
    builder.rect(Some("bricks"), vec2(2160., -600.), vec2(24., 516.)); // id=179
    builder.rect_graphics("question_mark", vec2(2100., 96.), vec2(24., 24.)); // id=182
    builder.rect(Some("bricks"), vec2(2676., -360.), vec2(24., 480.)); // id=185
    builder.rect(Some("barrier"), vec2(2400., -1200.), vec2(24., 960.)); // id=191
    builder.rect(Some("barrier"), vec2(2760., -1176.), vec2(24., 936.)); // id=196
    builder.rect(Some("bricks"), vec2(3120., -480.), vec2(24., 600.)); // id=197
    builder.polygon_graphics("caution", &[vec2(2772.901, -1296.588), vec2(2784.413, -1299.407), vec2(2786.917, -1293.965), vec2(2776.849, -1286.876)]); // id=198
    builder.polygon(Some("caution"), &[vec2(2772.886, -1296.614), vec2(2766.977, -1297.149), vec2(2760.019, -1293.509), vec2(2751.276, -1287.119), vec2(2744.32, -1274.668), vec2(2739.693, -1259.032), vec2(2739.983, -1245.686), vec2(2743.471, -1230.172), vec2(2776.767, -1286.577)]); // id=199
    builder.polygon(Some("caution"), &[vec2(2764.712, -1268.036), vec2(2761.655, -1249.53), vec2(2766.282, -1235.517), vec2(2743.083, -1231.794)]); // id=200
    builder.polygon(Some("caution"), &[vec2(2765.553, -1236.733), vec2(2781.242, -1216.961), vec2(2789.541, -1205.68), vec2(2789.12, -1201.498), vec2(2784.39, -1199.134), vec2(2770.485, -1201.566), vec2(2748.392, -1220.83), vec2(2742.89, -1231.686)]); // id=201
    builder.polygon(Some("bricks_dark"), &[vec2(2789.873, -1303.65), vec2(2793.891, -1296.69), vec2(2787.218, -1292.837), vec2(2783.199, -1299.797)]); // id=202
    builder.rect_graphics("question_mark", vec2(2760., -1332.), vec2(24., 24.)); // id=204
    builder.rect(Some("barrier"), vec2(2640., -1200.), vec2(240., 24.)); // id=211
    builder.rect(Some("bricks"), vec2(3336., -1560.), vec2(24., 1440.)); // id=213
    builder.rect(Some("bricks"), vec2(3576., -480.), vec2(24., 600.)); // id=214
    builder.polygon(Some("bricks"), &[vec2(3576., -264.), vec2(3432., -360.), vec2(3432., -480.), vec2(3576., -480.)]); // id=216
    builder.rect(Some("bricks"), vec2(3936., -1560.), vec2(24., 1440.)); // id=217
    builder.polygon(Some("barrier"), &[vec2(3384., -1152.), vec2(3930., -606.), vec2(3913.029, -589.029), vec2(3367.029, -1135.029)]); // id=218
    builder.rect(Some("bricks"), vec2(4080., -720.), vec2(24., 840.)); // id=219
    builder.rect(Some("bricks"), vec2(4080., -1560.), vec2(24., 720.)); // id=224
    builder.rect(Some("barrier"), vec2(3936., -1572.), vec2(168., 12.)); // id=225
    builder.rect(Some("bricks"), vec2(4104., -720.), vec2(2292., 24.)); // id=226
    builder.rect_graphics("question_mark", vec2(4176., -744.), vec2(24., 24.)); // id=227
    builder.rect_graphics("caution", vec2(1656., 60.), vec2(12., 58.)); // id=233
    builder.rect_graphics("question_mark", vec2(1620., 96.), vec2(24., 24.)); // id=234
    builder.rect_graphics("wood_dark", vec2(1728., -84.), vec2(24., 204.)); // id=241
    builder.rect_graphics("question_mark", vec2(1956., 96.), vec2(24., 24.)); // id=242
    builder.rect_graphics("question_mark", vec2(1104., 96.), vec2(24., 24.)); // id=244
    builder.rect_graphics("question_mark", vec2(1176., 96.), vec2(24., 24.)); // id=245
    builder.rect_graphics("question_mark", vec2(-528., 756.), vec2(24., 24.)); // id=104
    builder.rect_trigger(levels::TriggerKind::ShowText("Shoot a rocket under yourself to\nlaunch yourself into the air."), vec2(-84., 96.), vec2(24., 24.)); // id=99
    builder.polygon_trigger(levels::TriggerKind::Panic, &[vec2(-477.545, 718.182), vec2(-468.667, 700.), vec2(-461., 699.667), vec2(-380.333, 749.667), vec2(-379., 762.), vec2(-416.667, 780.667), vec2(-453.667, 769.667), vec2(-475.667, 743.667)]); // id=101
    builder.polygon_trigger(levels::TriggerKind::Hello, &[vec2(552., -600.), vec2(588., -720.), vec2(672., -600.)]); // id=102
    builder.rect_trigger(levels::TriggerKind::ShowText("This one is tricky!\nBut still possible with one rocket jump.\nHarness the power of penguin jank."), vec2(1440., 96.), vec2(24., 24.)); // id=103
    builder.rect_trigger(levels::TriggerKind::ShowText("banana secret"), vec2(-528., 756.), vec2(24., 24.)); // id=105
    builder.polygon_trigger(levels::TriggerKind::ShowText("banana"), &[vec2(1788., 120.), vec2(1776., 36.), vec2(1812., 24.), vec2(1884., 84.), vec2(1872., 120.)]); // id=184
    builder.rect_trigger(levels::TriggerKind::ShowText("You can rocket jump off of\nwalls too."), vec2(2100., 96.), vec2(24., 24.)); // id=183
    builder.rect_trigger(levels::TriggerKind::ShowText("you made it this high!\nthat's bananas"), vec2(2760., -1332.), vec2(24., 24.)); // id=205
    builder.rect_trigger(levels::TriggerKind::ShowText("to be continued!"), vec2(4176., -744.), vec2(24., 24.)); // id=228
    builder.rect_trigger(levels::TriggerKind::ShowText("If you can't make this jump,\nthere's a hidden hole ---->"), vec2(1620., 96.), vec2(24., 24.)); // id=235
    builder.rect_trigger(levels::TriggerKind::SetEyepatch(true), vec2(1728., -84.), vec2(24., 204.)); // id=236
    builder.rect_trigger(levels::TriggerKind::SetEyepatch(false), vec2(4080., -840.), vec2(24., 120.)); // id=240
    builder.rect_trigger(levels::TriggerKind::ShowText("The eyepatch means that you cannot\nshoot rockets when another rocket\nis already in flight."), vec2(1956., 96.), vec2(24., 24.)); // id=243
    builder.rect_trigger(levels::TriggerKind::ShowText("The penguin has a \"fuel meter\"\ndisplayed on its body. When you\nare out of fuel, you cannot shoot."), vec2(1104., 96.), vec2(24., 24.)); // id=246
    builder.rect_trigger(levels::TriggerKind::ShowText("Try aiming in the air and holding\nthe left mouse button to understand\nthe mechanism better."), vec2(1176., 96.), vec2(24., 24.)); // id=247
    builder.level_start(vec2(-156., 84.));
    builder.build_or_die()
}
