#![allow(clippy::excessive_precision, clippy::pedantic)]
/// This code is generated by `@/tiled/generate_code.py`.
/// Generated from file `test_level.tmj` on `2025-11-28 07:38:34.691486+00:00`.
use crate::levels;
use glam::{vec2, Vec2};

#[rustfmt::skip]
#[inline(never)]
pub fn build(mut builder: levels::LevelBuilder) -> levels::Level {
    builder.rect(Some("bricks"), vec2(-540., 120.), vec2(4692., 24.)); // id=4
    builder.rect(Some("barrier"), vec2(-504., -2400.), vec2(24., 2040.)); // id=27
    builder.rect(Some("barrier"), vec2(6396., -2400.), vec2(24., 1704.)); // id=28
    builder.polygon_graphics("wood_dark", &[vec2(-348., 120.), vec2(-324., 72.), vec2(-312., 72.), vec2(-336., 120.), vec2(-348., 120.)]); // id=30
    builder.polygon_graphics("wood_dark", &[vec2(-276., 120.), vec2(-300., 72.), vec2(-312., 72.), vec2(-288., 120.), vec2(-276., 120.)]); // id=31
    builder.rect_graphics("bricks_dark", vec2(120., 60.), vec2(72., 60.)); // id=32
    builder.rect(Some("bricks"), vec2(108., 36.), vec2(96., 24.)); // id=33
    builder.rect(Some("caution"), vec2(192., 60.), vec2(12., 60.)); // id=35
    builder.rect(Some("barrier"), vec2(-504., -276.), vec2(24., 396.)); // id=36
    builder.rect_graphics("barrier", vec2(-504., -360.), vec2(24., 84.)); // id=37
    builder.rect_graphics("wood_dark", vec2(-480., -300.), vec2(132., 12.)); // id=38
    builder.rect_graphics("wood_dark", vec2(-456., -288.), vec2(12., 12.)); // id=39
    builder.rect_graphics("wood_dark", vec2(-384., -288.), vec2(12., 12.)); // id=40
    builder.polygon(Some("caution"), &[vec2(-468., -228.), vec2(-468., -276.), vec2(-360., -276.), vec2(-336., -252.), vec2(-360., -228.)]); // id=42
    builder.rect(Some("barrier"), vec2(-1452., -1188.), vec2(12., 1668.)); // id=44
    builder.rect_graphics("bricks_dark", vec2(-600., 720.), vec2(72., 60.)); // id=45
    builder.rect(Some("bricks"), vec2(-624., 780.), vec2(264., 12.)); // id=47
    builder.polygon(Some("barrier"), &[vec2(-624., 792.), vec2(-624., 780.), vec2(-1440., 468.), vec2(-1440., 480.)]); // id=48
    builder.rect(None, vec2(-360., 144.), vec2(12., 648.)); // id=49
    builder.polygon_graphics("wood_dark", &[vec2(-612., 720.), vec2(-516., 720.), vec2(-564., 672.)]); // id=50
    builder.polygon_graphics("bricks_dark", &[vec2(-528., 708.), vec2(-540., 696.), vec2(-540., 672.), vec2(-528., 672.), vec2(-528., 708.)]); // id=52
    builder.rect(Some("bricks"), vec2(-720., 612.), vec2(48., 12.)); // id=55
    builder.polygon(Some("caution"), &[vec2(-348., 96.), vec2(-348., 48.), vec2(-276., 48.), vec2(-264., 72.), vec2(-276., 96.)]); // id=56
    builder.rect_graphics("bricks_dark", vec2(444., -48.), vec2(72., 168.)); // id=57
    builder.rect(Some("bricks"), vec2(432., -72.), vec2(96., 24.)); // id=58
    builder.rect(Some("caution"), vec2(516., -48.), vec2(12., 168.)); // id=59
    builder.rect_graphics("bricks_dark", vec2(864., -96.), vec2(72., 216.)); // id=60
    builder.rect(Some("bricks"), vec2(852., -120.), vec2(96., 24.)); // id=61
    builder.rect(Some("caution"), vec2(936., -96.), vec2(12., 216.)); // id=62
    builder.rect(Some("barrier"), vec2(600., -600.), vec2(24., 480.)); // id=63
    builder.rect(Some("barrier"), vec2(1056., -600.), vec2(24., 456.)); // id=65
    builder.rect_graphics("bricks_dark", vec2(1272., -156.), vec2(72., 276.)); // id=66
    builder.rect(Some("bricks"), vec2(1260., -180.), vec2(96., 24.)); // id=67
    builder.rect(Some("caution"), vec2(1344., -156.), vec2(12., 276.)); // id=68
    builder.rect(Some("barrier"), vec2(1416., -600.), vec2(24., 456.)); // id=69
    builder.rect_graphics("bricks_dark", vec2(1584., -180.), vec2(72., 300.)); // id=70
    builder.rect(Some("bricks"), vec2(1572., -200.), vec2(96., 24.)); // id=71
    builder.rect(Some("caution"), vec2(1656., -176.), vec2(12., 236.)); // id=72
    builder.rect(Some("wood"), vec2(1728., -3360.), vec2(24., 3276.)); // id=73
    builder.polygon_graphics("barrier", &[vec2(552., -600.), vec2(588., -720.), vec2(672., -600.)]); // id=83
    builder.polygon_graphics("caution", &[vec2(-471.06, 717.709), vec2(-467.746, 706.33), vec2(-461.78, 706.883), vec2(-460.675, 719.146)]); // id=84
    builder.polygon(Some("caution"), &[vec2(-471.088, 717.709), vec2(-474.506, 722.559), vec2(-474.833, 730.405), vec2(-473.671, 741.172), vec2(-466.365, 753.421), vec2(-455.138, 765.247), vec2(-443.435, 771.668), vec2(-430.074, 776.041), vec2(-460.455, 719.367)]); // id=85
    builder.polygon(Some("caution"), &[vec2(-450.424, 739.077), vec2(-435.926, 750.978), vec2(-421.477, 753.977), vec2(-429.852, 775.93)]); // id=86
    builder.polygon(Some("caution"), &[vec2(-422.893, 754.), vec2(-397.925, 750.3), vec2(-384.005, 748.753), vec2(-380.594, 751.209), vec2(-380.912, 756.486), vec2(-389.971, 767.313), vec2(-417.7, 776.814), vec2(-429.853, 776.151)]); // id=87
    builder.rect(Some("bricks_dark"), vec2(-468.685, 699.48), vec2(8.037, 7.706)); // id=88
    builder.rect_graphics("question_mark", vec2(-84., 96.), vec2(24., 24.)); // id=92
    builder.rect_graphics("question_mark", vec2(1440., 96.), vec2(24., 24.)); // id=98
    builder.polygon_graphics("caution", &[vec2(1788.028, 54.229), vec2(1791.342, 42.85), vec2(1797.308, 43.402), vec2(1798.413, 55.665)]); // id=165
    builder.polygon(Some("caution"), &[vec2(1788., 54.229), vec2(1784.582, 59.078), vec2(1784.255, 66.924), vec2(1785.418, 77.691), vec2(1792.723, 89.94), vec2(1803.95, 101.766), vec2(1815.654, 108.187), vec2(1830.832, 112.924), vec2(1798.633, 55.886)]); // id=166
    builder.polygon(Some("caution"), &[vec2(1808.665, 75.596), vec2(1823.163, 87.497), vec2(1837.611, 90.497), vec2(1829.236, 112.449)]); // id=167
    builder.polygon(Some("caution"), &[vec2(1836.195, 90.52), vec2(1861.163, 86.819), vec2(1875.083, 85.272), vec2(1878.494, 87.728), vec2(1878.176, 93.006), vec2(1869.117, 103.832), vec2(1841.388, 113.333), vec2(1829.235, 112.67)]); // id=168
    builder.rect(Some("bricks_dark"), vec2(1790.403, 36.), vec2(8.037, 7.706)); // id=169
    builder.rect(Some("bricks"), vec2(2256., -240.), vec2(24., 360.)); // id=178
    builder.rect(Some("bricks"), vec2(2160., -600.), vec2(24., 516.)); // id=179
    builder.rect_graphics("question_mark", vec2(2100., 96.), vec2(24., 24.)); // id=182
    builder.rect(Some("bricks"), vec2(2676., -360.), vec2(24., 480.)); // id=185
    builder.rect(Some("barrier"), vec2(2400., -1200.), vec2(24., 960.)); // id=191
    builder.rect(Some("barrier"), vec2(2760., -1176.), vec2(24., 936.)); // id=196
    builder.rect(Some("bricks"), vec2(3120., -480.), vec2(24., 600.)); // id=197
    builder.polygon_graphics("caution", &[vec2(2746.013, -1296.588), vec2(2757.524, -1299.407), vec2(2760.029, -1293.965), vec2(2749.961, -1286.876)]); // id=198
    builder.polygon(Some("caution"), &[vec2(2745.998, -1296.614), vec2(2740.089, -1297.149), vec2(2733.131, -1293.509), vec2(2724.388, -1287.119), vec2(2717.432, -1274.668), vec2(2712.804, -1259.032), vec2(2713.095, -1245.686), vec2(2716.583, -1230.172), vec2(2749.879, -1286.577)]); // id=199
    builder.polygon(Some("caution"), &[vec2(2737.824, -1268.036), vec2(2734.767, -1249.53), vec2(2739.394, -1235.517), vec2(2716.194, -1231.794)]); // id=200
    builder.polygon(Some("caution"), &[vec2(2738.664, -1236.733), vec2(2754.353, -1216.961), vec2(2762.653, -1205.68), vec2(2762.232, -1201.498), vec2(2757.502, -1199.134), vec2(2743.596, -1201.566), vec2(2721.504, -1220.83), vec2(2716.002, -1231.686)]); // id=201
    builder.polygon(Some("bricks_dark"), &[vec2(2762.984, -1303.65), vec2(2767.003, -1296.69), vec2(2760.33, -1292.837), vec2(2756.311, -1299.797)]); // id=202
    builder.rect_graphics("question_mark", vec2(2760., -1332.), vec2(24., 24.)); // id=204
    builder.rect(Some("barrier"), vec2(2640., -1200.), vec2(240., 24.)); // id=211
    builder.rect(Some("bricks"), vec2(3336., -1560.), vec2(24., 1440.)); // id=213
    builder.rect(Some("bricks"), vec2(3576., -480.), vec2(24., 600.)); // id=214
    builder.polygon(Some("bricks"), &[vec2(3576., -264.), vec2(3432., -360.), vec2(3432., -480.), vec2(3576., -480.)]); // id=216
    builder.rect(Some("bricks"), vec2(3936., -1560.), vec2(24., 1440.)); // id=217
    builder.polygon(Some("barrier"), &[vec2(3384., -1152.), vec2(3930., -606.), vec2(3913.029, -589.029), vec2(3367.029, -1135.029)]); // id=218
    builder.rect(Some("bricks"), vec2(4128., -720.), vec2(24., 840.)); // id=219
    builder.rect(Some("bricks"), vec2(4128., -1560.), vec2(24., 648.)); // id=224
    builder.rect(Some("barrier"), vec2(3936., -1572.), vec2(216., 12.)); // id=225
    builder.rect(Some("bricks"), vec2(4152., -720.), vec2(2244., 24.)); // id=226
    builder.rect_graphics("question_mark", vec2(4260., -744.), vec2(24., 24.)); // id=227
    builder.rect_graphics("caution", vec2(1656., 60.), vec2(12., 58.)); // id=233
    builder.rect_graphics("question_mark", vec2(1620., 96.), vec2(24., 24.)); // id=234
    builder.rect_graphics("wood_dark", vec2(1728., -84.), vec2(24., 204.)); // id=241
    builder.rect_graphics("question_mark", vec2(1956., 96.), vec2(24., 24.)); // id=242
    builder.rect_graphics("question_mark", vec2(1020., 96.), vec2(24., 24.)); // id=244
    builder.rect_graphics("question_mark", vec2(1092., 96.), vec2(24., 24.)); // id=245
    builder.rect_graphics("question_mark", vec2(-528., 756.), vec2(24., 24.)); // id=104
    builder.rect_graphics("barrier_danger", vec2(2424., -720.), vec2(24., 480.)); // id=252
    builder.rect_graphics("barrier_danger", vec2(2784., -720.), vec2(24., 480.)); // id=254
    builder.polygon_graphics("barrier_danger", &[vec2(3360., -264.), vec2(3480., -120.), vec2(3360., -120.)]); // id=261
    builder.rect_graphics("barrier_danger", vec2(4080., -360.), vec2(48., 24.)); // id=268
    builder.rect_graphics("barrier_danger", vec2(3960., -600.), vec2(48., 24.)); // id=269
    builder.rect_graphics("barrier_danger", vec2(3960., -144.), vec2(48., 24.)); // id=263
    builder.rect(Some("bricks"), vec2(4152., -936.), vec2(72., 24.)); // id=270
    builder.rect(Some("bricks"), vec2(4380., -852.), vec2(84., 12.)); // id=271
    builder.rect(Some("bricks"), vec2(4368., -1020.), vec2(12., 180.)); // id=272
    builder.rect(Some("bricks"), vec2(4380., -1020.), vec2(144., 12.)); // id=273
    builder.rect(Some("bricks"), vec2(4524., -1020.), vec2(12., 180.)); // id=274
    builder.rect_graphics("question_mark", vec2(4476., -744.), vec2(24., 24.)); // id=275
    builder.rect_graphics("barrier_move", vec2(4380., -1008.), vec2(48., 156.)); // id=278
    builder.polygon_graphics("caution", &[vec2(2803.122, -1300.94), vec2(2814.633, -1303.759), vec2(2817.138, -1298.317), vec2(2807.07, -1291.228)]); // id=280
    builder.polygon(Some("caution"), &[vec2(2803.112, -1300.96), vec2(2797.203, -1301.495), vec2(2790.245, -1297.855), vec2(2781.502, -1291.465), vec2(2774.546, -1279.014), vec2(2769.918, -1263.378), vec2(2770.209, -1250.032), vec2(2773.697, -1234.518), vec2(2806.993, -1290.923)]); // id=281
    builder.polygon(Some("caution"), &[vec2(2794.936, -1272.389), vec2(2791.879, -1253.883), vec2(2796.505, -1239.871), vec2(2773.306, -1236.148)]); // id=282
    builder.polygon(Some("caution"), &[vec2(2795.773, -1241.083), vec2(2811.462, -1221.311), vec2(2819.761, -1210.029), vec2(2819.34, -1205.847), vec2(2814.611, -1203.484), vec2(2800.705, -1205.916), vec2(2778.612, -1225.18), vec2(2773.11, -1236.035)]); // id=283
    builder.polygon(Some("bricks_dark"), &[vec2(2820.092, -1308.), vec2(2824.11, -1301.04), vec2(2817.437, -1297.187), vec2(2813.418, -1304.147)]); // id=284
    builder.polygon(Some("caution"), &[vec2(-95.897, 1896.684), vec2(-82.876, 1843.445), vec2(-55.203, 1844.796), vec2(-47.63, 1901.228)]); // id=290
    builder.polygon(Some("caution"), &[vec2(-96., 1896.682), vec2(-110.814, 1919.774), vec2(-110.744, 1956.089), vec2(-103.206, 2005.597), vec2(-66.989, 2060.718), vec2(-12.738, 2113.092), vec2(42.626, 2140.402), vec2(113.706, 2159.229), vec2(-46.54, 1902.197)]); // id=291
    builder.polygon(Some("caution"), &[vec2(3.729, 1991.233), vec2(73.106, 2043.295), vec2(140.462, 2054.242), vec2(106.188, 2157.35)]); // id=292
    builder.polygon(Some("caution"), &[vec2(133.927, 2054.658), vec2(248.532, 2032.532), vec2(312.531, 2022.584), vec2(328.784, 2033.242), vec2(328.38, 2057.689), vec2(288.707, 2109.532), vec2(162.509, 2159.011), vec2(106.232, 2158.396)]); // id=293
    builder.polygon(Some("bricks_dark"), &[vec2(-88.613, 1812.), vec2(-51.482, 1810.382), vec2(-49.93, 1845.982), vec2(-87.062, 1847.6)]); // id=294
    builder.rect(Some("wood"), vec2(-60., 996.), vec2(12., 816.)); // id=296
    builder.rect(Some("wood"), vec2(72., 996.), vec2(12., 84.)); // id=297
    builder.rect(Some("wood"), vec2(-60., 984.), vec2(144., 12.)); // id=298
    builder.rect(Some("wood"), vec2(12., 1068.), vec2(60., 12.)); // id=299
    builder.rect(Some("wood"), vec2(12., 1080.), vec2(12., 732.)); // id=300
    builder.polygon(Some("caution"), &[vec2(701.481, 2014.733), vec2(648.864, 1999.389), vec2(636.197, 2024.03), vec2(681.282, 2058.805)]); // id=308
    builder.polygon(Some("caution"), &[vec2(701.532, 2014.643), vec2(728.938, 2013.36), vec2(760.352, 2031.578), vec2(799.459, 2062.86), vec2(829.086, 2121.786), vec2(847.317, 2194.956), vec2(843.286, 2256.557), vec2(824.049, 2327.528), vec2(681.578, 2060.234)]); // id=309
    builder.polygon(Some("caution"), &[vec2(733.553, 2148.287), vec2(743.952, 2234.401), vec2(719.754, 2298.206), vec2(826.185, 2320.079)]); // id=310
    builder.polygon(Some("caution"), &[vec2(723.386, 2292.757), vec2(646.921, 2380.945), vec2(606.305, 2431.395), vec2(607.409, 2450.8), vec2(628.783, 2462.673), vec2(693.517, 2454.238), vec2(799.465, 2369.687), vec2(827.072, 2320.641)]); // id=311
    builder.polygon(Some("bricks_dark"), &[vec2(604.536, 2010.048), vec2(624.504, 1978.7), vec2(654.559, 1997.844), vec2(634.591, 2029.192)]); // id=312
    builder.polygon(Some("caution"), &[vec2(228.207, 2852.515), vec2(292.872, 2755.193), vec2(347.383, 2777.942), vec2(321.699, 2896.583)]); // id=313
    builder.polygon(Some("caution"), &[vec2(228., 2854.438), vec2(181.572, 2890.013), vec2(155.412, 2962.879), vec2(134.67, 3067.611), vec2(167.372, 3204.367), vec2(238.224, 3348.674), vec2(329.457, 3443.531), vec2(458.351, 3532.76), vec2(323.18, 2901.316)]); // id=314
    builder.polygon(Some("caution"), &[vec2(359.499, 3114.269), vec2(460.907, 3268.908), vec2(580.038, 3360.973), vec2(444.64, 3521.565)]); // id=315
    builder.polygon(Some("caution"), &[vec2(579.955, 3363.741), vec2(1796.058, 3979.05), vec2(1719.906, 4119.138), vec2(443.96, 3523.693)]); // id=316
    builder.polygon(Some("bricks_dark"), &[vec2(304.147, 2688.), vec2(379.774, 2711.647), vec2(357.103, 2784.155), vec2(281.476, 2760.508)]); // id=317
    builder.polygon(None, &[vec2(308.806, 2069.861), vec2(320.757, 2068.779), vec2(379.194, 2714.139), vec2(367.243, 2715.221)]); // id=325
    builder.polygon(None, &[vec2(24., 1812.), vec2(27.601, 1800.553), vec2(603.253, 1981.66), vec2(599.652, 1993.107)]); // id=326
    builder.polygon(None, &[vec2(646.75, 2466.914), vec2(654.146, 2457.464), vec2(1332.098, 2988.114), vec2(1324.702, 2997.564)]); // id=327
    builder.polygon(None, &[vec2(1321.191, 2982.908), vec2(1329.602, 2974.349), vec2(2342.117, 3969.347), vec2(2333.706, 3977.906)]); // id=330
    builder.polygon_graphics("barrier_danger", &[vec2(2208.054, 3950.687), vec2(2235.388, 3998.192), vec2(2214.436, 4016.32), vec2(2169.998, 3980.722)]); // id=332
    builder.polygon_graphics("barrier_danger", &[vec2(2208.129, 3950.616), vec2(2202.904, 3923.683), vec2(2177.783, 3897.459), vec2(2138.15, 3866.846), vec2(2073.895, 3851.971), vec2(1998.489, 3851.535), vec2(1939.582, 3869.999), vec2(1875.161, 3905.451), vec2(2168.54, 3980.772)]); // id=333
    builder.polygon_graphics("barrier_danger", &[vec2(2070.703, 3951.06), vec2(1984.569, 3961.292), vec2(1928.282, 3999.873), vec2(1881.895, 3901.617)]); // id=334
    builder.polygon_graphics("barrier_danger", &[vec2(1933.68, 3995.338), vec2(1866.043, 4090.466), vec2(1826.611, 4141.846), vec2(1807.494, 4145.356), vec2(1790.91, 4127.39), vec2(1783.82, 4062.495), vec2(1840.96, 3939.577), vec2(1882.099, 3901.169)]); // id=335
    builder.polygon_graphics("barrier_danger", &[vec2(2261.245, 4016.978), vec2(2235.5, 4043.783), vec2(2209.799, 4019.099), vec2(2235.545, 3992.294)]); // id=336
    builder.rect_graphics("question_mark", vec2(2352., 96.), vec2(24., 24.)); // id=338
    builder.rect_trigger(levels::TriggerKind::ShowText("Shoot a rocket under yourself to\nlaunch yourself into the air."), vec2(-84., 96.), vec2(24., 24.)); // id=99
    builder.polygon_trigger(levels::TriggerKind::Goto(LEVEL_OBJECT_295, levels::StatusIcon::Nice), &[vec2(-477.545, 718.182), vec2(-468.667, 700.), vec2(-461., 699.667), vec2(-380.333, 749.667), vec2(-379., 762.), vec2(-416.667, 780.667), vec2(-453.667, 769.667), vec2(-475.667, 743.667)]); // id=101
    builder.polygon_trigger(levels::TriggerKind::Hello, &[vec2(552., -600.), vec2(588., -720.), vec2(672., -600.)]); // id=102
    builder.rect_trigger(levels::TriggerKind::ShowText("This one is tricky!\nBut still possible with one rocket jump.\nHarness the power of penguin jank."), vec2(1440., 96.), vec2(24., 24.)); // id=103
    builder.rect_trigger(levels::TriggerKind::ShowText("banana secret"), vec2(-528., 756.), vec2(24., 24.)); // id=105
    builder.polygon_trigger(levels::TriggerKind::ShowText("banana"), &[vec2(1788., 120.), vec2(1776., 36.), vec2(1812., 24.), vec2(1884., 84.), vec2(1872., 120.)]); // id=184
    builder.rect_trigger(levels::TriggerKind::ShowText("You can rocket jump off of\nwalls too."), vec2(2100., 96.), vec2(24., 24.)); // id=183
    builder.rect_trigger(levels::TriggerKind::ShowText("you made it this high!\nthat's bananas"), vec2(2760., -1332.), vec2(24., 24.)); // id=205
    builder.rect_trigger(levels::TriggerKind::ShowText("to be continued!"), vec2(4260., -744.), vec2(24., 24.)); // id=228
    builder.rect_trigger(levels::TriggerKind::ShowText("If you can't make this jump,\nthere's a hidden hole ---->"), vec2(1620., 96.), vec2(24., 24.)); // id=235
    builder.rect_trigger(levels::TriggerKind::SetEyepatch(true), vec2(1728., -84.), vec2(24., 204.)); // id=236
    builder.rect_trigger(levels::TriggerKind::SetEyepatch(false), vec2(4200., -912.), vec2(24., 192.)); // id=240
    builder.rect_trigger(levels::TriggerKind::ShowText("The eyepatch means that you cannot\nshoot rockets when another rocket\nis already in flight."), vec2(1956., 96.), vec2(24., 24.)); // id=243
    builder.rect_trigger(levels::TriggerKind::ShowText("The penguin has a \"fuel meter\"\ndisplayed on its body. When you\nare out of fuel, you cannot shoot."), vec2(1020., 96.), vec2(24., 24.)); // id=246
    builder.rect_trigger(levels::TriggerKind::ShowText("Try aiming in the air and holding\nthe left mouse button to understand\nthe mechanism better."), vec2(1092., 96.), vec2(24., 24.)); // id=247
    builder.rect_trigger(levels::TriggerKind::Goto(LEVEL_OBJECT_253, levels::StatusIcon::Wrong), vec2(2424., -720.), vec2(24., 480.)); // id=251
    const LEVEL_OBJECT_253: Vec2 = vec2(2520., 72.); // id=253
    builder.rect_trigger(levels::TriggerKind::Goto(LEVEL_OBJECT_256, levels::StatusIcon::Wrong), vec2(2784., -720.), vec2(24., 480.)); // id=255
    const LEVEL_OBJECT_256: Vec2 = vec2(2880., 96.); // id=256
    builder.polygon_trigger(levels::TriggerKind::Goto(LEVEL_OBJECT_262, levels::StatusIcon::Wrong), &[vec2(3360., -264.), vec2(3480., -120.), vec2(3360., -120.)]); // id=260
    const LEVEL_OBJECT_262: Vec2 = vec2(3360., 96.); // id=262
    builder.rect_trigger(levels::TriggerKind::Goto(LEVEL_OBJECT_265, levels::StatusIcon::Wrong), vec2(3960., -144.), vec2(48., 24.)); // id=264
    const LEVEL_OBJECT_265: Vec2 = vec2(3960., 96.); // id=265
    builder.rect_trigger(levels::TriggerKind::Goto(LEVEL_OBJECT_265, levels::StatusIcon::Wrong), vec2(4080., -360.), vec2(48., 24.)); // id=266
    builder.rect_trigger(levels::TriggerKind::Goto(LEVEL_OBJECT_265, levels::StatusIcon::Wrong), vec2(3960., -600.), vec2(48., 24.)); // id=267
    builder.rect_trigger(levels::TriggerKind::ShowText("Go to the start"), vec2(4476., -744.), vec2(24., 24.)); // id=276
    builder.rect_trigger(levels::TriggerKind::Goto(LEVEL_OBJECT_279, levels::StatusIcon::Nice), vec2(4380., -1008.), vec2(48., 156.)); // id=277
    const LEVEL_OBJECT_279: Vec2 = vec2(-204., 48.); // id=279
    const LEVEL_OBJECT_295: Vec2 = vec2(36., 1044.); // id=295
    builder.polygon_trigger(levels::TriggerKind::Panic, &[vec2(1784.102, 4033.056), vec2(1859.141, 3914.979), vec2(1907.698, 3874.74), vec2(2027.309, 3838.555), vec2(2165.962, 3870.182), vec2(2301.41, 4022.099), vec2(2027.931, 4198.335), vec2(1797.821, 4115.989), vec2(1779.627, 4097.414)]); // id=337
    builder.rect_trigger(levels::TriggerKind::ShowText("Unlike real rockets, penguin rockets\ndon't inherit your velocity. E.g. if\nyou shoot a rocket directly downward\nwhile moving right, the rocket will\nexplode when it's to the left of you"), vec2(2352., 96.), vec2(24., 24.)); // id=339
    builder.rect_graphics("question_mark", vec2(2736., 96.), vec2(24., 24.)); // id=340
    builder.rect_trigger(levels::TriggerKind::ShowText("The game runs at 240 ticks/second.\nThe penguin's radius is 24.\nThe explosion radius is 42.\nExplosions live for 8 ticks.\nJust in case you like numbers."), vec2(2736., 96.), vec2(24., 24.)); // id=341
    builder.level_start(vec2(-204., 96.));
    builder.build_or_die()
}
