"""
Requires Python 3.12 or later. No other dependencies.

NB: in Python's "type annotation" system, `float` means `int | float`. Annoying.

NB2: polygon colliders are supposed to be convex for now, but we never check for that.
     if a polygon collider
"""

import json
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

if len(sys.argv) != 2:
    sys.stderr.write(
        "error: Expected exactly one argument, the path to the Tiled level (.tmj)\n"
    )
    sys.exit(1)

level_path = Path(sys.argv[1])

with open(level_path, "rb") as file:
    level = json.load(file)

layers = [layer for layer in level["layers"] if layer["name"] in ("Objects", "Triggers")]
if not layers:
    sys.stderr.write("error: Must have at least 'Objects' or 'Triggers' layer\n")
    sys.exit(1)

all_objects = [obj for layer in layers for obj in layer["objects"]]

TEMPLATE = """
#![allow(clippy::excessive_precision, clippy::pedantic)]
/// This code is generated by `@/tiled/generate_code.py`.
/// Generated from file `%(filename)s` on `%(datetime)s`.
use crate::levels;
use glam::vec2;

#[rustfmt::skip]
#[inline(never)]
pub fn build(mut builder: levels::LevelBuilder) -> levels::Level {
%(lines)s
    builder.level_start(%(level_start)s);
    builder.build_or_die()
}
""".strip()


def extract_property(obj: dict[str, Any], name: str) -> Any:
    for prop in obj.get("properties", []):
        if prop["name"] == name:
            return prop.get("value")
    raise Exception(f"Expected property {name!r} not found in object with id={obj["id"]}")


def trigger_action_expr(obj: dict[str, Any]) -> str:
    match extract_property(obj, "action"):
        case "Panic":
            return "levels::TriggerKind::Panic"
        case "Hello":
            return "levels::TriggerKind::Hello"
        case "DebugText":
            text = extract_property(obj, "text")
            return f"levels::TriggerKind::DebugText({json.dumps(text)})"
        case "ShowText":
            text = extract_property(obj, "text")
            return f"levels::TriggerKind::ShowText({json.dumps(text)})"
        case _:
            raise Exception(
                f"Unknown action in trigger object with id={obj['id']}"
            )


def maybe_texture_expr(obj: dict[str, Any]) -> str:
    for prop in obj.get("properties", []):
        if prop["name"] == "texture_id":
            value = prop["value"]
            assert '"' not in value and "\\" not in value
            if value in {"none", ""}:
                break
            return f'Some("{value}")'
    return "None"


def vec_expr(x: float, y: float) -> str:
    sx = f"{x:.3f}".rstrip("0")
    sy = f"{y:.3f}".rstrip("0")
    return f"vec2({sx}, {sy})"


def texture_expr(obj: dict[str, Any]) -> str:
    value = extract_property(obj, "texture_id")
    assert '"' not in value and "\\" not in value
    return f'"{value}"'


def polygon_to_expr(obj: list[dict[str, Any]], x: float, y: float) -> str:
    points = [vec_expr(x + p["x"], y + p["y"]) for p in obj]
    return "&[" + ", ".join(points) + "]"


lines: list[str] = []
level_start: str | None = None

for obj in all_objects:
    # Beware: Tiled exports are kinda cursed. For example, polygons have `x` and `y`
    # fields (which represent an offset) as well as `width` and `height` (which to my
    # knowledge don't represent anything and just chill out there).
    match obj:
        case {"polygon": polygon, "x": x, "y": y, "type": "Collider"}:
            texture = maybe_texture_expr(obj)
            points = polygon_to_expr(polygon, x, y)
            lines.append(f"builder.polygon({texture}, {points});")

        case {"polygon": polygon, "x": x, "y": y, "type": "Graphics"}:
            texture = texture_expr(obj)
            points = polygon_to_expr(polygon, x, y)
            lines.append(f"builder.polygon_graphics({texture}, {points});")

        case {"x": _, "y": _, "width": _, "height": _, "ellipse": True}:
            raise NotImplementedError("Ellipses are not supported yet")

        case {"x": _, "y": _, "width": _, "height": _, "text": _}:
            raise NotImplementedError("Text is not supported yet")

        case {"x": x, "y": y, "width": w, "height": h, "type": "Collider"}:
            texture = maybe_texture_expr(obj)
            lines.append(f"builder.rect({texture}, {vec_expr(x, y)}, {vec_expr(w, h)});")

        case {"x": x, "y": y, "width": w, "height": h, "type": "Graphics"}:
            texture = texture_expr(obj)
            lines.append(
                f"builder.rect_graphics({texture}, {vec_expr(x, y)}, {vec_expr(w, h)});"
            )

        case {"polygon": polygon, "x": x, "y": y, "type": "Trigger"}:
            action = trigger_action_expr(obj)
            points = polygon_to_expr(polygon, x, y)
            lines.append(
                f"builder.polygon_trigger({action}, {points});"
            )

        case {"x": x, "y": y, "width": w, "height": h, "type": "Trigger"}:
            action = trigger_action_expr(obj)
            lines.append(
                f"builder.rect_trigger({action}, {vec_expr(x, y)}, {vec_expr(w, h)});"
            )

        case {"x": x, "y": y, "type": "LevelStart"}:
            if level_start is not None:
                raise Exception("Duplicate LevelStart object")
            level_start = vec_expr(x, y)

        case other:
            raise Exception(f"Unknown object type with ID {obj.get('id')}")

if level_start is None:
    raise Exception("Expected a level start object in the level")

print(
    TEMPLATE
    % {
        "filename": level_path.name,
        "datetime": datetime.now(UTC),
        "level_start": level_start,
        "lines": "\n".join(["    " + line for line in lines]),
    }
)
