"""
Requires Python 3.12 or later. No other dependencies.

NB: in Python's "type annotation" system, `float` means `int | float`. Annoying.

NB2: polygon colliders are supposed to be convex for now, but we never check for that.
     if a polygon collider
"""

import json
import sys
from collections.abc import Iterator
from datetime import UTC, datetime
from math import cos, radians, sin
from pathlib import Path
from typing import Any

if len(sys.argv) != 2:
    sys.stderr.write(
        "error: Expected exactly one argument, the path to the Tiled level (.tmj)\n"
    )
    sys.exit(1)

level_path = Path(sys.argv[1])

with open(level_path, "rb") as file:
    level = json.load(file)

layers = [
    layer for layer in level["layers"] if layer["name"] in ("Objects", "Triggers")
]
if not layers:
    sys.stderr.write("error: Must have at least 'Objects' or 'Triggers' layer\n")
    sys.exit(1)

all_objects = [obj for layer in layers for obj in layer["objects"]]

TEMPLATE = """
#![allow(clippy::excessive_precision, clippy::pedantic)]
/// This code is generated by `@/tiled/generate_code.py`.
/// Generated from file `%(filename)s` on `%(datetime)s`.
use crate::levels;
use glam::{vec2, Vec2};

#[rustfmt::skip]
#[inline(never)]
pub fn build(mut builder: levels::LevelBuilder) -> levels::Level {
%(lines)s
    builder.level_start(%(level_start)s);
    builder.build_or_die()
}
""".strip()


def extract_property(obj: dict[str, Any], name: str, expected_type: str) -> Any:
    for prop in obj.get("properties", []):
        if prop["name"] == name:
            if prop.get("type") != expected_type:
                raise Exception(
                    f"Property {name!r} in object with id={obj['id']} "
                    "must be of type {expected_type!r}")
            return prop.get("value")
    raise Exception(f"Expected property {name!r} not found in object with id={obj['id']}")


def trigger_action_expr(obj: dict[str, Any]) -> str:
    match extract_property(obj, "action", "string"):
        case "Panic":
            return "levels::TriggerKind::Panic"
        case "Hello":
            return "levels::TriggerKind::Hello"
        case "DebugText":
            text = extract_property(obj, "text", "string")
            return f"levels::TriggerKind::DebugText({json.dumps(text)})"
        case "ShowText":
            text = extract_property(obj, "text", "string")
            return f"levels::TriggerKind::ShowText({json.dumps(text)})"
        case "SetEyepatch":
            enabled = extract_property(obj, "enabled", "bool")
            return f"levels::TriggerKind::SetEyepatch({str(enabled).lower()})"
        case "Goto":
            # this setup is not ideal, you will get an error on compilation instead of code generation
            target_id = extract_property(obj, "loc", "object")
            status_icon = extract_property(obj, "status_icon", "string")
            assert isinstance(target_id, int)
            if target_id == 0:
                raise Exception(f"Object with id={obj['id']} must have a location assigned")

            return f"levels::TriggerKind::Goto(LEVEL_OBJECT_{target_id}, levels::StatusIcon::{status_icon})"
        case _:
            raise Exception(f"Unknown action in trigger object with id={obj['id']}")


def maybe_texture_expr(obj: dict[str, Any]) -> str:
    for prop in obj.get("properties", []):
        if prop["name"] == "texture_id":
            value = prop["value"]
            assert '"' not in value and "\\" not in value
            if value in {"none", ""}:
                break
            return f'Some("{value}")'
    return "None"


def vec_expr(x: float, y: float) -> str:
    sx = f"{x:.3f}".rstrip("0")
    sy = f"{y:.3f}".rstrip("0")
    return f"vec2({sx}, {sy})"


def texture_expr(obj: dict[str, Any]) -> str:
    value = extract_property(obj, "texture_id", "string")
    assert '"' not in value and "\\" not in value
    return f'"{value}"'


def _rotate_around_origin(x: float, y: float, rad: float) -> tuple[float, float]:
    return (x * cos(rad) - y * sin(rad), y * cos(rad) + x * sin(rad))


def polygon_to_expr(
    obj: list[dict[str, Any]], rotation: float, cx: float, cy: float
) -> str:
    points = ((p["x"], p["y"]) for p in obj)
    points = (_rotate_around_origin(x, y, rotation) for x, y in points)
    points = [vec_expr(x + cx, y + cy) for x, y in points]
    return "&[" + ", ".join(points) + "]"


lines: list[str] = []
level_start: str | None = None


def render_obj(obj: dict[str, Any]) -> Iterator[str]:
    match obj:
        case {"ellipse": True}:
            raise NotImplementedError("Ellipses are not supported yet")

        case {"text": _}:
            raise NotImplementedError("Text is not supported yet")

        case {"id": id_, "x": x, "y": y, "type": "Location"}:
            yield f"const LEVEL_OBJECT_{id_}: Vec2 = {vec_expr(x, y)};"

        case {"polygon": polygon, "x": x, "y": y, "rotation": deg, "type": "Collider"}:
            texture = maybe_texture_expr(obj)
            points = polygon_to_expr(polygon, radians(deg), x, y)
            yield f"builder.polygon({texture}, {points});"

        case {"polygon": polygon, "x": x, "y": y, "rotation": deg, "type": "Trigger"}:
            action = trigger_action_expr(obj)
            points = polygon_to_expr(polygon, radians(deg), x, y)
            yield f"builder.polygon_trigger({action}, {points});"

        case {"polygon": polygon, "x": x, "y": y, "rotation": deg, "type": "Graphics"}:
            texture = texture_expr(obj)
            points = polygon_to_expr(polygon, radians(deg), x, y)
            yield f"builder.polygon_graphics({texture}, {points});"

        case {"x": x, "y": y, "width": w, "height": h, "rotation": deg} if abs(deg) > 0.001:
            # game only supports axis-aligned rects, so a rotated rect will be a polygon
            yield from render_obj({
                **obj,
                "polygon": [{"x": w*u, "y": h*v} for (u, v) in [(0, 0), (1, 0), (1, 1), (0,1)]],
            })

        case {"x": x, "y": y, "width": w, "height": h, "type": "Collider"}:
            texture = maybe_texture_expr(obj)
            yield f"builder.rect({texture}, {vec_expr(x, y)}, {vec_expr(w, h)});"

        case {"x": x, "y": y, "width": w, "height": h, "type": "Graphics"}:
            texture = texture_expr(obj)
            yield f"builder.rect_graphics({texture}, {vec_expr(x, y)}, {vec_expr(w, h)});"

        case {"x": x, "y": y, "width": w, "height": h, "type": "Trigger"}:
            action = trigger_action_expr(obj)
            yield f"builder.rect_trigger({action}, {vec_expr(x, y)}, {vec_expr(w, h)});"

        case _:
            raise Exception(f"Unknown object type with ID {obj.get('id')}")


for obj in all_objects:
    # Beware: Tiled exports are kinda cursed. For example, polygons have `x` and `y`
    # fields (which represent an offset) as well as `width` and `height` (which to my
    # knowledge don't represent anything and just chill out there).
    if obj.get("type") == "LevelStart":
        if level_start is not None:
            raise Exception("Duplicate LevelStart object")
        level_start = vec_expr(obj["x"], obj["y"])
    else:
        lines.extend(line + f" // id={obj['id']}" for line in render_obj(obj))


if level_start is None:
    raise Exception("Expected a level start object in the level")

print(
    TEMPLATE
    % {
        "filename": level_path.name,
        "datetime": datetime.now(UTC),
        "level_start": level_start,
        "lines": "\n".join(["    " + line for line in lines]),
    }
)
