name: Build and Deploy
on:
  push:
    branches:
      - trunk

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Output rust version
        run: rustup --version

      - name: Download wasm toolchain
        run: rustup target add wasm32-unknown-unknown

      - name: Lint with clippy on x86_64
        run: cargo clippy --all-targets --target x86_64-unknown-linux-gnu

      - name: Lint with clippy on wasm
        run: cargo clippy --all-targets --target wasm32-unknown-unknown

      - name: Test
        run: cargo test

      - name: Build Rust executable
        run: cargo build --release --target wasm32-unknown-unknown

      - name: Prepare Deployment Directory
        run: |
          cp -r ./html ./github-pages
          cp ./target/wasm32-unknown-unknown/release/penguin-game.wasm ./github-pages/penguin-game.wasm

      - name: Minify JavaScript
        run: |
          npm link @swc/core  # already installed in Github Actions :^)
          node <<EOF
            const fs = require("node:fs");
            const filename = "./github-pages/miniquad.js";
            const source = fs.readFileSync(filename);
            const minified = require("@swc/core").minifySync(source, {module: true}).code;
            fs.writeFileSync(filename, minified);
          EOF

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./github-pages

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
